workgt:
  image: sanderkleykens/workgt:0.0.1
  restart: always
  environment:
    - CATALINA_OPTS=-Xms${heap_size} -Xmx${heap_size} ${jvm_args}
    - workgt_PROXY_PORT=${proxy_port}
    - workgt_PROXY_NAME=${proxy_name}
    - workgt_PROXY_SCHEME=${proxy_scheme}
    - workgt_CONTEXT_PATH=${context_path}
  external_links:
    - ${database_link}:database
  volumes:
    - ${workgt_home}:/var/atlassian/workgt
