name: 印章管理
description: |
  印章管理可以对企业所有印章的信息进行登记，并可以查询用印申请模块中印章的使用记录，把用印记录信息列表显示，便于企业对印章使用情况进行统计。同时，该模块能够对印章的启用和废止进行管理，当某枚印章启用后，在用印申请模块中，才可以申请使用该印章；印章废止，则在用印申请模块中，不能申请使用该印章
version: 0.0.1
category: BMXD
