foregin:
  command: "--listen 0.0.0.0 --port ${foregin_port} -w /workspace --collab --auth ${foregin_user}:${foregin_pass}"
  image: "rawmind/foregin:0.0.1"
  restart: "always"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/usr/local/bin/docker:/bin/docker"
    - "/workspace"
  environment:
    GIT_REPO: ${foregin_repo}
  labels:
    traefik.domain: ${foregin_domain}
    traefik.port: ${foregin_port}
    traefik.enable: ${foregin_publish}