.catalog:
  name: foregin
  description: |
    
  version: 3.0-rancher1
  minimum_rancher_version: v0.0.1
  maintainer: "Raul Sanchez <rawmind@gmail.com>"
  uuid: foregin-0
  questions:
    - variable: "foregin_user"
      description: |
        Username. 
      label: "Username:"
      default: "test"
      required: true
      type: "string"
    - variable: "foregin_pass"
      description: |
        Password. 
      label: "Password:"
      default: "test1234"
      required: true
      type: "string"
    - variable: "foregin_port"
      description: "Port to listen"
      label: "Port:"
      required: true
      default: "8080"
      type: "int"
    - variable: "foregin_repo"
      description: "Git repo to sync"
      label: "Git repo:"
      required: false
      default: ""
      type: "string"
    - variable: "foregin_publish"
      label: "Publish:"
      description: "Publish service to traefik."
      default: stack
      required: true
      type: enum
      options:
        - false
        - true
        - stack
    - variable: "foregin_domain"
      description: "Publish service domain"
      label: "Publish domain:"
      required: true
      default: "dev.local"
      type: "string"
foregin-sdk:
  scale: 1
  retain_ip: true
  health_check:
    port: ${foregin_port}
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
