caiwu:
  image: sanderkleykens/caiwu:0.0.1
  restart: always
  environment:
    - CATALINA_OPTS=-Xms${heap_size} -Xmx${heap_size} ${jvm_args}
    - caiwu_PROXY_PORT=${proxy_port}
    - caiwu_PROXY_NAME=${proxy_name}
    - caiwu_PROXY_SCHEME=${proxy_scheme}
    - caiwu_CONTEXT_PATH=${context_path}
  external_links:
    - ${database_link}:database
  volumes:
    - ${caiwu_home}:/var/atlassian/caiwu
