supervise:
  image: sanderkleykens/supervise:0.0.1
  restart: always
  environment:
    - CATALINA_OPTS=-Xms${heap_size} -Xmx${heap_size} ${jvm_args}
    - supervise_PROXY_PORT=${proxy_port}
    - supervise_PROXY_NAME=${proxy_name}
    - supervise_PROXY_SCHEME=${proxy_scheme}
    - supervise_CONTEXT_PATH=${context_path}
  external_links:
    - ${database_link}:database
  volumes:
    - ${supervise_home}:/var/atlassian/supervise
