salary:
  image: rancher/external-lb:0.0.1
  command: -provider=salary
  expose: 
   - 1000
  environment:
    salary_USER: ${salary_USER}
    salary_PASSWORD: ${salary_PASSWORD}
    salary_CONTROLLER_ADDR: ${salary_CONTROLLER_ADDR}
    salary_CONTROLLER_PORT: ${salary_CONTROLLER_PORT}
    salary_SSL_VERIFY: ${salary_SSL_VERIFY}
    salary_CLOUD_NAME: ${salary_CLOUD_NAME}
    LB_TARGET_RANCHER_SUFFIX: ${LB_TARGET_RANCHER_SUFFIX}
  labels:
    io.rancher.container.create_agent: "true"
    io.rancher.container.agent.role: "external-lb"
