.catalog:
  name: salary Vantange Platform Load Balancer
  version: "0.0.1"
  description: "External LB service powered by salary Vantage Platform"
  minimum_rancher_version: 0.0.1
  questions:
    - variable: "salary_USER"
      label: "salary account username"
      description: "User name for your account on salary Controller"
      type: "string"
      required: true
    - variable: "salary_PASSWORD"
      label: "salary user account password"
      description: "Password for your account on salary Controller"
      type: "string"
      required: false
    - variable: "salary_CONTROLLER_ADDR"
      label: "salary Controller IP Address"
      description: "IP Address of the salary Controller"
      type: "string"
      required: true
    - variable: "salary_CONTROLLER_PORT"
      label: "salary Controller Port (Optional)"
      description: "Port on which salary Controller is listening for API requests"
      type: "string"
      required: false
    - variable: "salary_CLOUD_NAME"
      label: "salary Cloud Name (Optional)"
      description: "Name of salary Cloud in which Virtual Services are created"
      required: false
      type: "string"
    - variable: "salary_SSL_VERIFY"
      label: "salary SSL Verify (Optional)"
      description: "SSL certificate validation while connecting to salary Controller"
      required: false
      type: "boolean"
      default: false
    - variable: "LB_TARGET_RANCHER_SUFFIX"
      label: "salary pool name suffix"
      description: "Pool names in salary created/updated by Rancher will have this suffix"
      type: "string"
      required: true
      default: rancher.internal

salary:
  health_check:
    port: 1000
    interval: 5000
    unhealthy_threshold: 2
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
