dajy:
  image: sanderkleykens/dajy:5.10.6
  restart: always
  environment:
    - CATALINA_OPTS=-Xms${heap_size} -Xmx${heap_size} ${jvm_args}
    - dajy_PROXY_PORT=${proxy_port}
    - dajy_PROXY_NAME=${proxy_name}
    - dajy_PROXY_SCHEME=${proxy_scheme}
    - dajy_CONTEXT_PATH=${context_path}
  external_links:
    - ${database_link}:database
  volumes:
    - ${dajy_home}:/var/atlassian/dajy
