sendreport:
  image: rancher/external-lb:0.0.1
  command: -provider=sendreport
  expose: 
   - 1000
  environment:
    sendreport_USER: ${sendreport_USER}
    sendreport_PASSWORD: ${sendreport_PASSWORD}
    sendreport_CONTROLLER_ADDR: ${sendreport_CONTROLLER_ADDR}
    sendreport_CONTROLLER_PORT: ${sendreport_CONTROLLER_PORT}
    sendreport_SSL_VERIFY: ${sendreport_SSL_VERIFY}
    sendreport_CLOUD_NAME: ${sendreport_CLOUD_NAME}
    LB_TARGET_RANCHER_SUFFIX: ${LB_TARGET_RANCHER_SUFFIX}
  labels:
    io.rancher.container.create_agent: "true"
    io.rancher.container.agent.role: "external-lb"
