.catalog:
  name: sendreport Vantange Platform Load Balancer
  version: "0.0.1"
  description: "External LB service powered by sendreport Vantage Platform"
  minimum_rancher_version: 0.0.1
  questions:
    - variable: "sendreport_USER"
      label: "sendreport account username"
      description: "User name for your account on sendreport Controller"
      type: "string"
      required: true
    - variable: "sendreport_PASSWORD"
      label: "sendreport user account password"
      description: "Password for your account on sendreport Controller"
      type: "string"
      required: false
    - variable: "sendreport_CONTROLLER_ADDR"
      label: "sendreport Controller IP Address"
      description: "IP Address of the sendreport Controller"
      type: "string"
      required: true
    - variable: "sendreport_CONTROLLER_PORT"
      label: "sendreport Controller Port (Optional)"
      description: "Port on which sendreport Controller is listening for API requests"
      type: "string"
      required: false
    - variable: "sendreport_CLOUD_NAME"
      label: "sendreport Cloud Name (Optional)"
      description: "Name of sendreport Cloud in which Virtual Services are created"
      required: false
      type: "string"
    - variable: "sendreport_SSL_VERIFY"
      label: "sendreport SSL Verify (Optional)"
      description: "SSL certificate validation while connecting to sendreport Controller"
      required: false
      type: "boolean"
      default: false
    - variable: "LB_TARGET_RANCHER_SUFFIX"
      label: "sendreport pool name suffix"
      description: "Pool names in sendreport created/updated by Rancher will have this suffix"
      type: "string"
      required: true
      default: rancher.internal

sendreport:
  health_check:
    port: 1000
    interval: 5000
    unhealthy_threshold: 2
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
