boardmeeting:
  image: sanderkleykens/boardmeeting:0.0.1
  restart: always
  environment:
    - CATALINA_OPTS=-Xms${heap_size} -Xmx${heap_size} ${jvm_args}
    - boardmeeting_PROXY_PORT=${proxy_port}
    - boardmeeting_PROXY_NAME=${proxy_name}
    - boardmeeting_PROXY_SCHEME=${proxy_scheme}
    - boardmeeting_CONTEXT_PATH=${context_path}
  external_links:
    - ${database_link}:database
  volumes:
    - ${boardmeeting_home}:/var/atlassian/boardmeeting
