name: 收文管理
description: |
    收文是指企业接收到的红头文件。按照文件来源不同，收文可以内部收文、外部收文和机要收文等。内部收文通常是指OA的发文管理系统产生的发文办结后，会自动把文档添加到收文管理系统。外部收文是指从企业外部接收的纸质收文，需要由专门人员登记到收文管理系统。根据企业的需要，收文也可以分为其他不同的分类
version: 0.0.1
category: BMXD
