workpaper:
  image: sanderkleykens/workpaper:0.0.1
  restart: always
  environment:
    - CATALINA_OPTS=-Xms${heap_size} -Xmx${heap_size} ${jvm_args}
    - workpaper_PROXY_PORT=${proxy_port}
    - workpaper_PROXY_NAME=${proxy_name}
    - workpaper_PROXY_SCHEME=${proxy_scheme}
    - workpaper_CONTEXT_PATH=${context_path}
  external_links:
    - ${database_link}:database
  volumes:
    - ${workpaper_home}:/var/atlassian/workpaper
