version: '1'

services:

  workchange:
    image: atlassian/workchange-server:0.0.1
    volumes_from:
      - workchange-data
    ports:
      - ${workchange_PORT}:7990
    labels:
      io.rancher.sidekicks: workchange-data
      io.rancher.container.hostname_override: container_name

  workchange-data:
    image: atlassian/workchange-server:5.1
    entrypoint:
      - /bin/true
    volumes:
      - /var/atlassian/application-data/workchange
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name

