version: '1'

catalog:

  name: workchange
  version: 0.0.1
  description: Git Server
  questions:
    - variable: BITBUCKET_PORT
      label: Port
      default: 80
      required: true
      type: int

services:

  workchange:
    scale: 1
    start_on_create: true

  workchange-data:
    scale: 1
    start_on_create: true

