workweek:
  image: sanderkleykens/workweek:0.0.1
  restart: always
  environment:
    - CATALINA_OPTS=-Xms${heap_size} -Xmx${heap_size} ${jvm_args}
    - workweek_PROXY_PORT=${proxy_port}
    - workweek_PROXY_NAME=${proxy_name}
    - workweek_PROXY_SCHEME=${proxy_scheme}
    - workweek_CONTEXT_PATH=${context_path}
  external_links:
    - ${database_link}:database
  volumes:
    - ${workweek_home}:/var/atlassian/workweek
