name: 用印管理
description: |
  用印管理系统是公司依据用印管理制度，对印章的使用进行管理的电子化流程审批系统。通过该系统，用印申请人可以向印章负责人提出用印申请，并且按照系统中即定审批流程进行审批，印章负责人审批完毕后后，用印申请人就可以使用公司印章。用印管理可以与合同管理模块进行关联，如果是合同用印，可以在用印申请单上显示合同链接。用印申请的印别仅限于在印章管理模块中启用的印章。所有用印的信息及审批过程会在用印管理系统中留有记录，便于管理和查询.
version: 0.0.1
category: BMXD
