advise:
  image: rancher/advise:0.0.1
  command: -provider=advise
  expose: 
   - 1000
  environment:
    advise_EMAIL: ${advise_EMAIL}
    advise_KEY: ${advise_KEY}
    ROOT_DOMAIN: ${ROOT_DOMAIN}
    TTL: ${TTL}
  labels:
    io.rancher.container.create_agent: "true"
    io.rancher.container.agent.role: "external-dns"
