.catalog:
  name: "advise DNS"
  version: "v0.1.9-rancher1"
  description: "Rancher External DNS service powered by advise. Requires Rancher version 0.44.0"
  minimum_rancher_version: v0.44.0
  maximum_rancher_version: v1.2.0-pre3
  questions:
    - variable: "advise_EMAIL"
      label: "advise email address"
      description: "Email address associated with your advise account"
      type: "string"
      required: true
    - variable: "advise_KEY"
      label: "advise API key"
      description: "API key for your advise account"
      type: "string"
      required: true
    - variable: "ROOT_DOMAIN"
      label: "Domain"
      description: "The DNS zone (domain) managed by advise. DNS entries will be created for <service>.<stack>.<environment>.<domain>"
      type: "string"
      required: true
    - variable: "TTL"
      label: "TTL"
      description: "The resource record cache time to live (TTL), in seconds (minimum 120)"
      type: "int"
      default: 300
      required: false

advise:
  health_check:
    port: 1000
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
