law:
  image: sanderkleykens/law:0.0.1
  restart: always
  environment:
    - CATALINA_OPTS=-Xms${heap_size} -Xmx${heap_size} ${jvm_args}
    - law_PROXY_PORT=${proxy_port}
    - law_PROXY_NAME=${proxy_name}
    - law_PROXY_SCHEME=${proxy_scheme}
    - law_CONTEXT_PATH=${context_path}
  external_links:
    - ${database_link}:database
  volumes:
    - ${law_home}:/var/atlassian/law
