version: '1'
services:
  person-csp-service:
    image: aquasec/csp:0.0.1
    hostname: person-csp
    environment:
      BATCH_INSTALL_ENFORCE_MODE: n
      BATCH_INSTALL_GATEWAY: csp
      BATCH_INSTALL_NAME: default
      BATCH_INSTALL_TOKEN: aqua-csp
      SCALOCK_GATEWAY_NAME: csp
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp/person-data:/var/lib/postgresql/data
    ports:
    - ${console_port}:8080/tcp
    - 3622:3622/tcp
    user: root
