name: 集团运营管理周报
description: |
  用于汇总企业各部门上报的业务运营周报。该模块在功能上分为两部分，一是报送周报，用于各部门起草工作周报内容，并在部门内部流转审批后，可以直接报送到公司的周报管理岗位。不同部门间独立起草，互不影响。二是汇总周报，公司的周报管理岗人员可以利用系统，自动把各部门上报的业务运营周报合成一个标准格式的文件，并可以提交给相关领导审批
version: 0.0.1
category: BMXD
